import { Router } from 'express';
import manualExecutionRoutes from './execution.routes.js';
import { systemRouter } from '../modules/system/system.routes.js';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes.js';
import { paperTradingRouter } from '../modules/paper-trading/paper-trading.routes.js';
import { liveTradingRouter } from '../modules/live-trading/live-trading.routes.js';

import { journalRouter } from '../modules/journal/journal.routes.js';
import { analyticsRouter } from '../modules/analytics/analytics.routes.js';
import { challengeRouter } from '../modules/challenge/challenge.routes.js';
import { settingsRouter } from '../modules/settings/settings.routes.js';
import { strategyRouter } from '../modules/strategy/strategy.routes.js';
import { decisionRouter } from '../modules/decision/decision.routes.js';
import { aiDecisionRouter } from '../modules/ai-decision/ai-decision.routes.js';
import { rulesRouter } from '../modules/rules/rules.routes.js';
import { marketDataRouter } from '../modules/market-data/market-data.routes.js';
import { replayBacktestRouter } from '../modules/replay-backtest/replay-backtest.routes.js';
import { executionRouter as executionEngineRouter } from '../modules/execution-engine/index.js';
import { executionRouter as executionAdapterRouter } from '../modules/execution/execution.routes.js';
import { tradingViewRouter } from '../modules/tradingview-adapter/tradingview.routes.js';
import { systemIntegrationRouter } from '../modules/system-integration/systemIntegration.routes.js';
import { productionRouter } from '../modules/production/production.routes.js';
import { indicatorRouter } from '../modules/indicator-engine/indicator.routes.js';
import { indicatorValidationRouter } from '../modules/indicator-validation/indicatorValidation.routes.js';
import { strategyProfileRouter } from '../modules/strategy-profile/strategyProfile.routes.js';
import { tradeAccountingRouter } from '../modules/trade-accounting/tradeAccounting.routes.js';
import { realtimeOperationsRouter } from '../modules/realtime-operations/realtimeOperations.routes.js';
import { strategyOptimizationRouter } from '../modules/strategy-optimization/strategyOptimization.routes.js';
import { operationsCenterRouter } from '../modules/operations-center/operationsCenter.routes.js';
import { tradeReviewRouter } from '../modules/trade-review/tradeReview.routes.js';
import { shadowTradingRouter } from '../modules/shadow-trading/shadowTrading.routes.js';
import { newsRouter } from '../modules/news/news.routes.js';
import { deltaExchangeRouter } from '../modules/delta-exchange/index.js';
import { portfolioRouter } from '../modules/portfolio/index.js';
import { enterpriseApiRouter } from './api.js';
import copilotRoutes from './copilot.routes.js';
import healthRoutes from './health.routes.js';
import orderBlockRoutes from './orderBlocks.routes.js';
import adminRoutes from './admin.routes.js';
import ordersRoutes from './orders.routes.js';

export const apiRouter = Router();

import scannerRoutes from './scanner.routes.js';

apiRouter.use('/health', healthRoutes);
apiRouter.use('/admin', adminRoutes);
apiRouter.use('/orders', ordersRoutes);
apiRouter.use('/portfolio', portfolioRouter);
apiRouter.use('/delta', deltaExchangeRouter);
apiRouter.use('/news', newsRouter);
apiRouter.use('/core', enterpriseApiRouter);
apiRouter.use('/system', systemRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/paper-trading', paperTradingRouter);
apiRouter.use('/live-trading', liveTradingRouter);
apiRouter.use('/scanner', scannerRoutes);
apiRouter.use('/copilot', copilotRoutes);
apiRouter.use('/order-blocks', orderBlockRoutes);

apiRouter.use('/journal', journalRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/challenge', challengeRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/strategy', strategyRouter);
apiRouter.use('/decision', decisionRouter);
apiRouter.use('/ai-decision', aiDecisionRouter);
apiRouter.use('/rules', rulesRouter);
apiRouter.use('/market-data', marketDataRouter);
apiRouter.use('/replay', replayBacktestRouter);
const combinedExecutionRouter = Router();
console.log('Adapter routes:', executionAdapterRouter.stack.map(l => l.route?.path));
combinedExecutionRouter.use(executionEngineRouter);
combinedExecutionRouter.use(executionAdapterRouter);
combinedExecutionRouter.use(manualExecutionRoutes);

apiRouter.use('/execution', combinedExecutionRouter);
apiRouter.use('/tradingview', tradingViewRouter);
apiRouter.use('/system-integration', systemIntegrationRouter);
apiRouter.use('/production', productionRouter);
apiRouter.use('/indicator', indicatorRouter);
apiRouter.use('/indicator-validation', indicatorValidationRouter);
apiRouter.use('/strategy-profile', strategyProfileRouter);
apiRouter.use('/trade-accounting', tradeAccountingRouter);
apiRouter.use('/realtime-operations', realtimeOperationsRouter);
apiRouter.use('/strategy-optimization', strategyOptimizationRouter);
apiRouter.use('/operations-center', operationsCenterRouter);
apiRouter.use('/trade-review', tradeReviewRouter);
apiRouter.use('/shadow-trading', shadowTradingRouter);
