import { Router } from 'express';
import authMiddleware from './middleware/authenticate.js';
import manualExecutionRoutes from './execution.routes.js';
import { systemRouter } from '../modules/system/system.routes.js';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes.js';
import { paperTradingRouter } from '../modules/paper-trading/paper-trading.routes.js';
import { liveTradingRouter } from '../modules/live-trading/live-trading.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';

import { journalRouter } from '../modules/journal/journal.routes.js';
import { analyticsRouter } from '../modules/analytics/analytics.routes.js';
import { challengeRouter } from '../modules/challenge/challenge.routes.js';
import { settingsRouter } from '../modules/settings/settings.routes.js';
import { strategyRouter } from '../modules/strategy/strategy.routes.js';
import { decisionRouter } from '../modules/decision/decision.routes.js';
import { aiDecisionRouter } from '../modules/ai-decision/ai-decision.routes.js';
import { rulesRouter } from '../modules/rules/rules.routes.js';
import { marketDataRouter } from '../modules/market-data/market-data.routes.js';
import { replayBacktestRouter } from '../modules/replay-backtest/replay-backtest.routes.js';
import { executionRouter as executionEngineRouter } from '../modules/execution-engine/index.js';
import { tradingViewRouter } from '../modules/tradingview-adapter/tradingview.routes.js';
import { systemIntegrationRouter } from '../modules/system-integration/systemIntegration.routes.js';
import { productionRouter } from '../modules/production/production.routes.js';
import { indicatorRouter } from '../modules/indicator-engine/indicator.routes.js';
import { indicatorValidationRouter } from '../modules/indicator-validation/indicator-validation.routes.js';
import { strategyProfileRouter } from '../modules/strategy-profile/strategyProfile.routes.js';
import { tradeAccountingRouter } from '../modules/trade-accounting/tradeAccounting.routes.js';
import { realtimeOperationsRouter } from '../modules/realtime-operations/realtimeOperations.routes.js';
import { strategyOptimizationRouter } from '../modules/strategy-optimization/strategyOptimization.routes.js';
import { operationsCenterRouter } from '../modules/operations-center/operationsCenter.routes.js';
import { tradeReviewRouter } from '../modules/trade-review/tradeReview.routes.js';
import { shadowTradingRouter } from '../modules/shadow-trading/shadowTrading.routes.js';
import { newsRouter } from '../modules/news/news.routes.js';
import { deltaExchangeRouter } from '../modules/delta-exchange/index.js';
import { portfolioRouter } from '../modules/portfolio/index.js';
import { enterpriseApiRouter } from './api.js';
import copilotRoutes from './copilot.routes.js';
import healthRoutes from './health.routes.js';
import orderBlockRoutes from './orderBlocks.routes.js';
import adminRoutes from './admin.routes.js';
import ordersRoutes from './orders.routes.js';

export const apiRouter = Router();

import scannerRoutes from './scanner.routes.js';
import indicatorDebugRoute from './indicatorDebug.route.js';

apiRouter.use('/health', healthRoutes);
apiRouter.use(indicatorDebugRoute);
apiRouter.use('/auth', authRouter);
apiRouter.use('/admin', authMiddleware, adminRoutes);
apiRouter.use('/orders', authMiddleware, ordersRoutes);
apiRouter.use('/portfolio', authMiddleware, portfolioRouter);
apiRouter.use('/delta', authMiddleware, deltaExchangeRouter);
apiRouter.use('/news', newsRouter);
apiRouter.use('/core', authMiddleware, enterpriseApiRouter);
apiRouter.use('/system', authMiddleware, systemRouter);
apiRouter.use('/dashboard', authMiddleware, dashboardRouter);
apiRouter.use('/paper-trading', authMiddleware, paperTradingRouter);
apiRouter.use('/live-trading', authMiddleware, liveTradingRouter);
apiRouter.use('/scanner', authMiddleware, scannerRoutes);
apiRouter.use('/copilot', authMiddleware, copilotRoutes);
apiRouter.use('/order-blocks', authMiddleware, orderBlockRoutes);

apiRouter.use('/journal', authMiddleware, journalRouter);
apiRouter.use('/analytics', analyticsRouter);
apiRouter.use('/challenge', authMiddleware, challengeRouter);
apiRouter.use('/settings', authMiddleware, settingsRouter);
apiRouter.use('/strategy', authMiddleware, strategyRouter);
apiRouter.use('/decision', authMiddleware, decisionRouter);
apiRouter.use('/ai-decision', authMiddleware, aiDecisionRouter);
apiRouter.use('/rules', authMiddleware, rulesRouter);
apiRouter.use('/market-data', authMiddleware, marketDataRouter);
apiRouter.use('/replay', authMiddleware, replayBacktestRouter);
const combinedExecutionRouter = Router();
combinedExecutionRouter.use(executionEngineRouter);
combinedExecutionRouter.use(manualExecutionRoutes);

apiRouter.use('/execution', authMiddleware, combinedExecutionRouter);
apiRouter.use('/tradingview', authMiddleware, tradingViewRouter);
apiRouter.use('/system-integration', authMiddleware, systemIntegrationRouter);
apiRouter.use('/production', authMiddleware, productionRouter);
apiRouter.use('/indicators', authMiddleware, indicatorRouter);
apiRouter.use('/indicator', authMiddleware, indicatorRouter);
apiRouter.use('/indicator-validation', authMiddleware, indicatorValidationRouter);
apiRouter.use('/strategy-profile', authMiddleware, strategyProfileRouter);
apiRouter.use('/trade-accounting', authMiddleware, tradeAccountingRouter);
apiRouter.use('/realtime-operations', authMiddleware, realtimeOperationsRouter);
apiRouter.use('/strategy-optimization', authMiddleware, strategyOptimizationRouter);
apiRouter.use('/operations-center', authMiddleware, operationsCenterRouter);
apiRouter.use('/trade-review', authMiddleware, tradeReviewRouter);
apiRouter.use('/shadow-trading', authMiddleware, shadowTradingRouter);
